export const MODAL_TRIGGER = 'MODAL_TRIGGER';

export const PHONE_LOADING_BEGIN = 'PHONE_LOADING_BEGIN';
export const PHONE_LOADING_DONE = 'PHONE_LOADING_DONE';
export const PHONE_LOADING_ERROR = 'PHONE_LOADING_ERROR';
export const PHONE_SET_ERROR = 'PHONE_SET_ERROR';

export const CLIENT_LOADING_BEGIN = 'CLIENT_LOADING_BEGIN';
export const CLIENT_LOADING_DONE = 'CLIENT_LOADING_DONE';
export const CLIENT_LOADING_ERROR = 'CLIENT_LOADING_ERROR';
export const CLIENT_SET_ERROR = 'CLIENT_SET_ERROR';
export const CLIENT_SET_TICK = 'CLIENT_SET_TICK';
export const CLIENT_SET_RULES_TICK = 'CLIENT_SET_RULES_TICK';
export const CLIENT_SET_DATA_TICK = 'CLIENT_SET_DATA_TICK';

export const CAR_LOADING_BEGIN = 'CAR_LOADING_BEGIN';
export const CAR_LOADING_DONE = 'CAR_LOADING_DONE';
export const CAR_LOADING_ERROR = 'CAR_LOADING_ERROR';
export const CAR_SET_ERROR = 'CAR_SET_ERROR';

export const MODAL_LOADING_BEGIN = 'MODAL_LOADING_BEGIN';
export const MODAL_LOADING_DONE = 'MODAL_LOADING_DONE';
export const MODAL_LOADING_ERROR = 'MODAL_LOADING_ERROR';
export const MODAL_SET_ERROR = 'MODAL_SET_ERROR';

export const ADDITIONAL_ADD_CLIENT = 'ADDITIONAL_ADD_CLIENT';
export const ADDITIONAL_REMOVE_CLIENT = 'ADDITIONAL_REMOVE_CLIENT';

export const ADDITIONAL_ADD_CAR = 'ADDITIONAL_ADD_CAR';
export const ADDITIONAL_REMOVE_CAR = 'ADDITIONAL_REMOVE_CAR';

export const TOPLINE_SET_MESSAGE = 'TOPLINE_SET_MESSAGE';

export const PRICING_SET_PREPRICE = 'PRICING_SET_PREPRICE';

export const PRICING_SET_FINALPRICE_STANDALONE = 'PRICING_SET_FINALPRICE_STANDALONE';
