export const MODAL_TRIGGER = 'MODAL_TRIGGER';

export const PHONE_LOADING_BEGIN = 'PHONE_LOADING_BEGIN';
export const PHONE_LOADING_DONE = 'PHONE_LOADING_DONE';
export const PHONE_LOADING_ERROR = 'PHONE_LOADING_ERROR';
export const PHONE_SET_ERROR = 'PHONE_SET_ERROR';

export const CLIENT_SET_ERROR = 'CLIENT_SET_ERROR';
