export const MODAL_TRIGGER = 'MODAL_TRIGGER';
export const PHONE_LOADING_BEGIN = 'PHONE_LOADING_BEGIN';
export const PHONE_LOADING_DONE = 'PHONE_LOADING_DONE';
export const PHONE_LOADING_ERROR = 'PHONE_LOADING_ERROR';
